CREATE TABLE usuarios (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	documento VARCHAR(18) NOT NULL UNIQUE,
	senhaCriptografada VARCHAR(100) NOT NULL
);

CREATE TABLE clientes ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	documento VARCHAR(18) NOT NULL UNIQUE,
	telefone VARCHAR(15),
	dataCadastro TIMESTAMP NOT NULL DEFAULT NOW(),
	
	usuarioId INTEGER NOT NULL,

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id)
);

CREATE TABLE enderecoClientes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	logradouro VARCHAR(180),
    numero VARCHAR(10),
    complemento VARCHAR(50),
    bairro VARCHAR(45),
	estado VARCHAR(45),
    cidade VARCHAR(45),
    cep VARCHAR(10),
	
	clienteId INTEGER NOT NULL,

	CONSTRAINT fk_cliente FOREIGN KEY (clienteId) REFERENCES clientes(id)

);

CREATE TABLE pedidos ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dataPedido TIMESTAMP NOT NULL DEFAULT NOW(),
	valorTotal NUMERIC(10,2) NOT NULL,
	
	usuarioId INTEGER NOT NULL,
	clienteId INTEGER NOT NULL,

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id),
	CONSTRAINT fk_cliente FOREIGN KEY (clienteId) REFERENCES clientes(id)
);

CREATE TABLE joias ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	descricao TEXT,
	preco NUMERIC(10,2) NOT NULL,
	quantidade INTEGER NOT NULL,
	
	usuarioId INTEGER NOT NULL,

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id)
);

CREATE TABLE joiasPedidos ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	quantidade INTEGER NOT NULL,
	precoUnidade NUMERIC(10,2) NOT NULL,
	subtotal NUMERIC(10,2) NOT NULL,

	pedidoId INTEGER NOT NULL,
	joiaId INTEGER NOT NULL,	

	CONSTRAINT fk_pedido FOREIGN KEY (pedidoId) REFERENCES pedidos(id),
	CONSTRAINT fk_joia FOREIGN KEY (joiaId) REFERENCES joias(id)
);

CREATE TABLE pagamentos ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	numeroParcela INTEGER, NOT NULL,
	qtdParcelas INTEGER NOT NULL,
	valorParcela NUMERIC(10,2) NOT NULL,
	dataPagamento TIMESTAMP,
	dataVencimento TIMESTAMP NOT NULL,
	status VARCHAR(15),
	formaPagamento VARCHAR(15),

	usuarioId INTEGER NOT NULL,	
	pedidoId INTEGER NOT NULL,
	clienteId INTEGER NOT NULL,

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id),
	CONSTRAINT fk_pedido FOREIGN KEY (pedidoId) REFERENCES pedidos(id),
	CONSTRAINT fk_cliente FOREIGN KEY (clienteId) REFERENCES clientes(id)
);

