CREATE TABLE usuarios (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	documento VARCHAR(18) NOT NULL UNIQUE,
	senhaCriptografada VARCHAR(100) NOT NULL
);

CREATE TABLE clientes ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	documento VARCHAR(18) NOT NULL UNIQUE,
	telefone VARCHAR(15),
	dataCadastro TIMESTAMP NOT NULL DEFAULT NOW(),
	
	usuarioId INTEGER NOT NULL,

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id)
);

CREATE TABLE enderecoClientes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	logradouro VARCHAR(180),
    numero VARCHAR(10),
    complemento VARCHAR(50),
    bairro VARCHAR(45),
	estado VARCHAR(45),
    cidade VARCHAR(45),
    cep VARCHAR(10),
	
	clienteId INTEGER NOT NULL,

	CONSTRAINT fk_cliente FOREIGN KEY (clienteId) REFERENCES clientes(id)

);

CREATE TABLE pedidos ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dataPedido TIMESTAMP NOT NULL DEFAULT NOW(),
	valorTotal NUMERIC(10,2),
	
	usuarioId INTEGER NOT NULL,
	clienteId INTEGER NOT NULL,
	tipo INTEGER NULL,

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id),
	CONSTRAINT fk_cliente FOREIGN KEY (clienteId) REFERENCES clientes(id)
);

CREATE TABLE joias ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	codigo VARCHAR(255) UNIQUE,
	nome VARCHAR(100) NOT NULL,
	descricao TEXT,
	status TEXT,
	preco NUMERIC(10,2) NOT NULL,
	quantidade INTEGER NOT NULL,
	imagemurl VARCHAR(500),
	imagempublicid VARCHAR(500),
	usuarioId INTEGER NOT NULL,
	

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id)
);

CREATE TABLE joiasPedidos ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	quantidade INTEGER NOT NULL,
	precoUnidade NUMERIC(10,2) NOT NULL,
	subtotal NUMERIC(10,2) NOT NULL,
	

	pedidoId INTEGER NOT NULL,
	joiaId INTEGER,	
	nomeJoia VARCHAR(100);
	descricaoJoia TEXT;
	imagemUrlJoia VARCHAR(500);

	CONSTRAINT fk_pedido FOREIGN KEY (pedidoId) REFERENCES pedidos(id),
);

CREATE TABLE pagamentos ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	numeroParcela INTEGER, NOT NULL,
	qtdParcelas INTEGER NOT NULL,
	valorParcela NUMERIC(10,2) NOT NULL,
	dataPagamento TIMESTAMP,
	dataVencimento TIMESTAMP NOT NULL,
	status VARCHAR(15),
	formaPagamento VARCHAR(15),
	valorpagamento NUMERIC(18,2) NOT NULL,

	usuarioId INTEGER NOT NULL,	
	pedidoId INTEGER NOT NULL,
	clienteId INTEGER NOT NULL,

	CONSTRAINT fk_usuario FOREIGN KEY (usuarioId) REFERENCES usuarios(id),
	CONSTRAINT fk_pedido FOREIGN KEY (pedidoId) REFERENCES pedidos(id),
	CONSTRAINT fk_cliente FOREIGN KEY (clienteId) REFERENCES clientes(id)
);

-- CLIENTES → USUARIOS
ALTER TABLE clientes DROP CONSTRAINT fk_usuario;
ALTER TABLE clientes ADD CONSTRAINT fk_usuario
    FOREIGN KEY (usuarioId) REFERENCES usuarios(id) ON DELETE CASCADE;

-- ENDERECOSCLIENTES → CLIENTES
ALTER TABLE enderecoClientes DROP CONSTRAINT fk_cliente;
ALTER TABLE enderecoClientes ADD CONSTRAINT fk_cliente
    FOREIGN KEY (clienteId) REFERENCES clientes(id) ON DELETE CASCADE;

-- PEDIDOS → USUARIOS
ALTER TABLE pedidos DROP CONSTRAINT fk_usuario;
ALTER TABLE pedidos ADD CONSTRAINT fk_usuario
    FOREIGN KEY (usuarioId) REFERENCES usuarios(id) ON DELETE CASCADE;

-- PEDIDOS → CLIENTES
ALTER TABLE pedidos DROP CONSTRAINT fk_cliente;
ALTER TABLE pedidos ADD CONSTRAINT fk_cliente
    FOREIGN KEY (clienteId) REFERENCES clientes(id) ON DELETE CASCADE;

-- JOIAS → USUARIOS
ALTER TABLE joias DROP CONSTRAINT fk_usuario;
ALTER TABLE joias ADD CONSTRAINT fk_usuario
    FOREIGN KEY (usuarioId) REFERENCES usuarios(id) ON DELETE CASCADE;

-- JOIASPEDIDOS → PEDIDOS
ALTER TABLE joiasPedidos DROP CONSTRAINT fk_pedido;
ALTER TABLE joiasPedidos ADD CONSTRAINT fk_pedido
    FOREIGN KEY (pedidoId) REFERENCES pedidos(id) ON DELETE CASCADE;

-- PAGAMENTOS → USUARIOS
ALTER TABLE pagamentos DROP CONSTRAINT fk_usuario;
ALTER TABLE pagamentos ADD CONSTRAINT fk_usuario
    FOREIGN KEY (usuarioId) REFERENCES usuarios(id) ON DELETE CASCADE;

-- PAGAMENTOS → PEDIDOS
ALTER TABLE pagamentos DROP CONSTRAINT fk_pedido;
ALTER TABLE pagamentos ADD CONSTRAINT fk_pedido
    FOREIGN KEY (pedidoId) REFERENCES pedidos(id) ON DELETE CASCADE;

-- PAGAMENTOS → CLIENTES
ALTER TABLE pagamentos DROP CONSTRAINT fk_cliente;
ALTER TABLE pagamentos ADD CONSTRAINT fk_cliente
    FOREIGN KEY (clienteId) REFERENCES clientes(id) ON DELETE CASCADE;
